---
# tasks file for common

- name: set timezone to Europe/Moscow
  timezone:
    name: "{{ region }}/{{ city }}"

- block:
    - name: create swap file
      shell: fallocate -l {{ swap_size }} /swapfile
      args:
        creates: "/{{swap_path}}"

    - name: set the correct permissions
      file:
        path: "/{{swap_path}}"
        owner: root
        group: root
        mode: '0600'

    - name: make the file a swap file
      shell: mkswap "/{{swap_path}}"
      when: ansible_facts.swapfree_mb == 0

    - name: enable the swap file
      shell: swapon "/{{swap_path}}"
      when: ansible_facts.swapfree_mb == 0

    - name: add swap file to fstab
      mount:
        name: none
        src: "/{{swap_path}}"
        fstype: swap
        opts: sw
        passno: 0
        dump: 0
        state: present